[web]
web ansible_host=192.168.56.11

[db]
db ansible_host=192.168.56.12

[debian:children]
web

[rocky:children]
db

[lab:children]
debian
rocky

[lab:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=/home/vagrant/.ssh/id_ed25519
